### ISSUE TITLE
[umbrella] Road to public release

### ISSUE THREAD

**Issue by grabbou** [rise-tools/rise-tools#17]
This issue is a work in progress and items will change as we add more things onto the roadmap.

1.0 release ("core features")
- [ ] Runtime validation of JSON payloads inside `ws-client` and `ws-server`
- [ ] #50
- [ ] Improve performance - maintain references while updating deep parts of the state
- [x] Implement currently ignored unit tests in the `react` package
- [x] Improve forms with async event handlers and implement error handling 
- [ ] Figure out marketing (value proposition, slogan etc.) - [pages like this](https://shipfa.st) have nice angle
- [ ] Support `web` in the playground
- [x] In-memory Data Source for using the `<Template />` component standalone
- [ ] Documentation for each package
- [ ] Guides
- [ ] Add links to App Store / Play Store to our app

----
1.1 release ("additional server capabilities")
- [x] JSON RPC Data Source
- [x] JSX transform on the server

----
X release 
- [ ] bindings in other technologies (e.g. Java, Golang)

**Comment by grabbou** [comment]
Some other questions to resolve at some point:
- local/user specific data
- pulling data in real-time and updating UI
- searching/filtering elements in a List - this may require a higher-order component, or some sort of server-side hooks to make it work

**Comment by ericvicenti** [comment]
hey we did it!
