### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by ericvicenti** [rise-tools/rise-tools#96]
- [ ] Prep Talk
   - [x] Create example for the talk
   - [x] Test latest additions (models) and fix bugs if any
- [x] Docs Site
- [x] #113 
- [x] #63 
- [x] Prep Social Media Launch Activity
- [x] Collect feedback from friends and domain experts
- [x] Ship Updated Playground App
  - [x] iOS
  - [x] Android
- [ ] Ship NPM Packages
  - [x] Move "state" (client-side) to experimental section (#82)
  - [x] Alpha for dogfooding tests
  - [x] Beta for launch
- [x] Add Functionality to Kit
  - [x] Haptics Actions

**Comment by grabbou** [comment]
TBD tomorrow

**Saturday:**
- [ ] Extract all remaining 3 component from kit into separate packages
- [ ] Re-export everything from umbrella kit package
- [ ] [Clean-up namespaces (drop "@" to make them shorter)](https://github.com/rise-tools/rise-tools/issues/122)
- [ ] Build and release all packages to "npm" with new version

**Sunday:**
- [ ] https://github.com/rise-tools/rise-tools/issues/107
- [ ] Ship new build of Rise to TestFlight / Play Store

**Comment by grabbou** [comment]
Notes from the meeting:

- native dependencies get their standalone module
- higher order components go to kit
- kitchen-sink is reexport to make it easier for people

**Comment by ericvicenti** [comment]
Seeing as we launched a week ago, I'd say we are done with the launch checklist 🎉😂
